name: sparrow-ipc
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Libraries dependencies
  - flatbuffers
  - nlohmann_json
  - sparrow-devel >=1.1.2
  - sparrow-json-reader
  - doctest
  # Documentation dependencies
  - doxygen
  - graphviz
