name: sparrow-ipc
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Libraries dependencies
  - flatbuffers
  - nlohmann_json
  - sparrow-devel
  - sparrow-json-reader
  - lz4
  # Testing dependencies
  - doctest
  # Documentation dependencies
  - doxygen
  - graphviz
