name: Conan
on:
    workflow_dispatch:
    pull_request:
    push:
      branches: [main]

jobs:
  conan-package:
    runs-on: ubuntu-24.04

    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Conan Environment
        uses: hankhsu1996/setup-conan@v1.1.0
        with:
          cache-dependencies: true
          cache-tool: true

      - name: Install conan dependencies
        run: |
          conan profile detect --force
          conan install . --output-folder=build --build=missing -s:a compiler.cppstd=20 -o:a build_tests=True -o sparrow:with_json_reader=True

      - name: CMake configuration
        run: |
          cmake --preset conan-release \
          -DSPARROW_IPC_BUILD_TESTS=ON \
          -DFETCH_DEPENDENCIES_WITH_CMAKE=MISSING \
          -DCMAKE_C_COMPILER_LAUNCHER=sccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build tests
        working-directory: build/build/Release
        run: cmake --build . --config Release --target test_sparrow_ipc_lib

      - name: Run tests
        working-directory: build/build/Release
        run: cmake --build . --config Release --target run_tests_with_junit_report

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
